version: 0.2 
 
#env: 
  #variables: 
     # key: "value" 
     # key: "value" 
  #parameter-store: 
     # key: "value" 
     # key: "value" 
 
phases: 
  install:
    runtime-versions:
        docker: 18     
  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    # update the following line with your own region
    - $(aws ecr get-login --no-include-email --region us-east-2) 
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    # update the following line with the name of your own ECR repository
    - docker build -t srebbyca/nodejs-app/`echo ${ENV}|tr [:upper:] [:lower:]`-web-app . 
    # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
    - docker tag srebbyca/nodejs-app/`echo ${ENV}|tr [:upper:] [:lower:]`-web-app:latest 542068092988.dkr.ecr.us-east-2.amazonaws.com/srebbyca/nodejs-app/`echo ${ENV}|tr [:upper:] [:lower:]`-web-app:latest 
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    - docker push 542068092988.dkr.ecr.us-east-2.amazonaws.com/srebbyca/nodejs-app/`echo ${ENV}|tr [:upper:] [:lower:]`-web-app:latest
    - $(aws ecr describe-repositories --output text | awk '{print $5}' | while read line; do  aws ecr list-images --repository-name $line --filter tagStatus=UNTAGGED --query 'imageIds[*]' --output text | while read imageId; do aws ecr batch-delete-image --repository-name $line --image-ids imageDigest=$imageId; done; done)

#artifacts: 
    # - location 
    # - location 
  #discard-paths: yes 
  #base-directory: location 
#cache: 
  #paths: 
    # - paths 
 
